name: Release new version

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GIT_AUTHOR_EMAIL: ${{vars.AUTHOR_EMAIL}}
  GIT_AUTHOR_NAME: $${{vars.AUTHOR_NAME}}
  GIT_COMMITTER_EMAIL: ${{vars.AUTHOR_EMAIL}}
  GIT_COMMITTER_NAME: $${{vars.AUTHOR_NAME}}

jobs:
  version:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.action.outputs.tag }}
      version: ${{ steps.action.outputs.version }}
      commit_start: ${{ steps.action.outputs.commit_start}}
      commit_end: ${{ steps.action.outputs.commit_end}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate new version
        id: action
        uses: pier-oliviert/actions@93f3e1eebdec7c429087475f126c54702de3b01b
        with:
          args: /actions/index.ts create version
          repo: ${{ github.repository}}

  changelog:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ["version"]
    outputs:
      changelog: ${{steps.action.outputs.changelog}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate Changelog
        uses: pier-oliviert/actions@93f3e1eebdec7c429087475f126c54702de3b01b
        id: action
        env:
          GIT_CLIFF__CHANGELOG__HEADER: ""
          GIT_CLIFF__CHANGELOG__FOOTER: ""
        with:
          args: /actions/index.ts create changelogs
          version: ${{needs.version.outputs.version}}
          commit_start: ${{needs.version.outputs.commit_start}}
          commit_end: ${{needs.version.outputs.commit_end}}

  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ["version", "changelog"]
    outputs:
      upload_url: ${{steps.action.outputs.upload_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Helm package
        id: action
        uses: pier-oliviert/actions@93f3e1eebdec7c429087475f126c54702de3b01b
        with:
          args: /actions/index.ts create release
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository}}
          version: ${{ needs.version.outputs.version }}
          tag: ${{ needs.version.outputs.tag }}
          changelog: ${{ needs.changelog.outputs.changelog }}

  helm:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ["version", "release"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Deploy Helm package
        uses: pier-oliviert/actions@93f3e1eebdec7c429087475f126c54702de3b01b
        with:
          args: /actions/index.ts create helm
          repo: ${{ github.repository}}
          release_upload_url: ${{ needs.release.outputs.upload_url }}
          version: ${{ needs.version.outputs.version }}
